---
title: "README"
author: "Elena Lopez"
date: "16/06/2020"
output: html_document
---

# CLV Analysis

## Objective
Develop a machine learning model to predict the CLV of newly customers using historical of customer transactions from a online retail business and multiple linear regression. 


## Dataset

Dataset contains daily online transactions of customers across the world from December 2010 to December 2011.
Dataset was obtained from UCI Machine Learning Repository. The dataset can be found in this link: 
http://archive.ics.uci.edu/ml/datasets/online+retail
The dataset contains 541909 rows and 8 columns.


## Key steps

- 1. Data cleaning -- work with missing values, duplicates, unique values.
- 2. EDA -- identify description and distribution of columns, key insights on customer profiles (top-ten country's customer, transactions across time, top-ten products)
- 3. CLV Calculation using historical data -- calculate the following indicators:
      a. Average order value
      b. Purchase frequency
      c. Repeat rate
      d. Churn rate
      e. Profit margin
- 4. Prediction Model for CLV -> apply machine learning model to predict the CLV of newly customers using sklearn.

- Appendix: Model using statsmodels.api package (it is not relevant in this case because I am trying to predict, not assess relationship and correlation)

## References

- https://towardsdatascience.com/data-driven-growth-with-python-part-3-customer-lifetime-value-prediction-6017802f2e0f

- https://data-science-blog.com/blog/2020/03/19/how-important-is-customer-lifetime-value/

- https://www.datacamp.com/community/tutorials/customer-life-time-value